spring:
  jpa:
    show-sql: false
  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

server:
  error:
    include-message: never
    include-binding-errors: never

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

logging:
  level:
    root: WARN
    com.thulirix: INFO
    org.springframework.security: WARN
